<a href="https://colab.research.google.com/github/aditigupta217/DL/blob/main/CNN_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import Perceptron    # Used for simple linear classification tasks.

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential     # Sequential lets you build a neural network layer-by-layer in Keras.

from tensorflow.keras.layers import Dense     #Dense makes the final predictions
from tensorflow.keras.layers import Conv2D     # Conv2D extracts features
from tensorflow.keras.layers import Flatten    # Flatten reshapes them

from tensorflow.keras.layers import MaxPooling2D     # MaxPooling2D reduces size
from tensorflow.keras.layers import Dropout          # Dropout prevents overfitting

from tensorflow.keras.utils import to_categorical     # converts numeric class labels into one-hot

In [51]:
df = pd.read_csv("mnist_train.csv")
df_test = pd.read_csv("mnist_test.csv")

In [52]:
df.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [53]:
df.shape

(60000, 785)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to 28x28
dtypes: int64(785)
memory usage: 359.3 MB

In [55]:
df.isnull().sum()

label    0
1x1      0
1x2      0
1x3      0
1x4      0
        ..
28x24    0
28x25    0
28x26    0
28x27    0
28x28    0
Length: 785, dtype: int64

In [72]:
# preprocess
X_train = df.drop("label", axis = 1).values
y_train = df["label"].values
X_test = df_test.drop("label", axis = 1).values
y_test = df_test["label"].values

In [73]:
print(df.columns)

Index(['label', '1x1', '1x2', '1x3', '1x4', '1x5', '1x6', '1x7', '1x8', '1x9',
       ...
       '28x19', '28x20', '28x21', '28x22', '28x23', '28x24', '28x25', '28x26',
       '28x27', '28x28'],
      dtype='object', length=785)

In [74]:
X_train = X_train.astype("float32")/255.0
X_test = X_test.astype("float32")/255.0

In [75]:
X_train_img = X_train.reshape(-1,28,28)
X_test_img = X_test.reshape(-1,28,28)

In [76]:
y_test_cat = to_categorical(y_test,10)
y_train_cat = to_categorical(y_train,10)

In [77]:
print(y_train.shape)
print(y_test.shape)

(60000,)
(10000,)

In [62]:
perceptron = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(10,activation="softmax")
])

In [78]:
perceptron.compile(optimizer = "sgd", loss="categorical_crossentropy", metrics=["accuracy"])

In [79]:
history_percp = perceptron.fit(
    X_train_img,
    y_train_cat,
    epochs=5,
    batch_size=32,
    validation_data=(X_test_img, y_test_cat),
    verbose=1
)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8923 - loss: 0.4010 - val_accuracy: 0.9035 - val_loss: 0.3647
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8976 - loss: 0.3751 - val_accuracy: 0.9071 - val_loss: 0.3463
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9015 - loss: 0.3589 - val_accuracy: 0.9091 - val_loss: 0.3345
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9039 - loss: 0.3473 - val_accuracy: 0.9115 - val_loss: 0.3254
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9059 - loss: 0.3385 - val_accuracy: 0.9124 - val_loss: 0.3186

In [81]:
acc_percp = perceptron.evaluate(X_test_img, y_test_cat, verbose=0)[1]

In [82]:
acc_percp

0.9124000072479248

In [86]:
#ANN
ann = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(128,activation="relu"),
    Dense(64,activation="relu"),
    Dense(10,activation="softmax")
])

In [87]:
ann.compile(optimizer="adam",loss="categorical_crossentropy", metrics= ["accuracy"])

In [88]:
history_ann = ann.fit(X_train_img, y_train_cat, epochs=5, batch_size=32,
validation_data=(X_test_img, y_test_cat), verbose=1)

Epoch 1/5
Epoch 2/5
Epoch 3/5
Epoch 4/5
Epoch 5/5

In [90]:
acc_ann = ann.evaluate(X_test_img, y_test_cat, verbose=0)[1]

In [91]:
acc_ann

0.9764999747276306

In [101]:
X_train_cnn = X_train.reshape(-1, 28, 28,1)
X_test_cnn = X_test.reshape (-1, 28, 28, 1)

In [98]:
cnn = Sequential([
    Conv2D(32, kernel_size=(3,3), activation="relu", input_shape=(28,28,1)),
    MaxPooling2D(pool_size=(2,2)),
    Conv2D(64, kernel_size=(3,3),
    activation="relu"),
    MaxPooling2D(pool_size=(2,2)),
    Flatten(),
    Dense (128, activation="relu"),
    Dropout (0.5),
    Dense (10, activation="softmax")
])

In [99]:
cnn.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [102]:
history_cnn = cnn.fit(X_train_cnn, y_train_cat, epochs=5, batch_size=32,
validation_data=(X_test_cnn,y_test_cat), verbose=1)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 57s 28ms/step - accuracy: 0.9366 - loss: 0.2095 - val_accuracy: 0.9838 - val_loss: 0.0486
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 54s 29ms/step - accuracy: 0.9762 - loss: 0.0798 - val_accuracy: 0.9880 - val_loss: 0.0355
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 81s 28ms/step - accuracy: 0.9834 - loss: 0.0578 - val_accuracy: 0.9913 - val_loss: 0.0276
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 54s 29ms/step - accuracy: 0.9864 - loss: 0.0454 - val_accuracy: 0.9905 - val_loss: 0.0281
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 52s 28ms/step - accuracy: 0.9883 - loss: 0.0398 - val_accuracy: 0.9912 - val_loss: 0.0240

In [104]:
acc_cnn = cnn.evaluate(X_test_cnn, y_test_cat, verbose=0)[1]

In [105]:
acc_cnn

0.9911999702453613